### PR TITLE
Update docs for python library

### PR DESCRIPTION
**Pull request by ldynia**
This PR carries updates to python documentation. Now, people who want to install the package directly in their project can do it with pip -- skipping pip registry.

### CODE REVIEW

**Comment by zekth** [comment]
@sudosubin could you check on this one as you contributed on the python implementations? 🙏

**Comment by tasn** [comment]
The README is correct, the problem is that we haven't released to PyPi yet. It's now been fixed (it's on pypi).

**Comment by sudosubin** [comment]
All content appears to be correct and great.
However, since the package was distributed on [PyPI](https://pypi.org/project/standardwebhooks/), so it would be better if a section for installing from PyPI was added :D

**Comment by ldynia** [comment]
@sudosubin I have added the requested changes and expanded the example section.

**Pull request closed without merging**
